name: "Verify And Deploy Infrastructure"

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-2"
  TF_STATE_BUCKET: "blockchain-state-rawal29-2025"
  TF_WORKING_DIR: "./infrastructure"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: "Apply & Publish"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install web3 python-dotenv

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Identify PR Number
        uses: actions/github-script@v6
        id: get-pr
        with:
          script: |
            const { data } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
            });
            return (data.length === 0) ? "none" : data[0].number;
          result-encoding: string

      - name: Download Approved Plan
        id: download-plan
        run: |
          PR_NUM="${{ steps.get-pr.outputs.result }}"
          if [ "$PR_NUM" == "none" ]; then
             echo "Direct Push detected. No S3 plan available."
          else
             echo "Downloading Plan for PR #${PR_NUM}"
             aws s3 cp s3://${{ env.TF_STATE_BUCKET }}/plans/pr-${PR_NUM}.tfplan ${{ env.TF_WORKING_DIR }}/tfplan.binary || true
          fi

      - name: Enforce Security Gate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          if [ ! -f "tfplan.binary" ]; then
            echo "CRITICAL: No authorized plan found! Pipeline Aborted."
            exit 1
          fi

      - name: Blockchain Verify
        env:
          ETHEREUM_RPC_URL: ${{ secrets.ETHEREUM_RPC_URL }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
        run: |
          CONTRACT_ADDR=$(grep 'contract_address' infrastructure/terraform.tfvars | cut -d '"' -f 2)
          export CONTRACT_ADDRESS=$CONTRACT_ADDR
          python scripts/tf_guard.py verify ${{ env.TF_WORKING_DIR }}/tfplan.binary

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan.binary

      - name: Publish Artifacts & Dashboard
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          RAW_ARTIFACT=$(terraform output -raw artifact_bucket_name)
          RAW_WEBSITE=$(terraform output -raw website_bucket_name)
          DASHBOARD_URL=$(terraform output -raw dashboard_url)
          
          ARTIFACT_BUCKET=$(echo "$RAW_ARTIFACT" | grep -o 'blockchain-artifacts-[0-9]*' | head -n 1)
          WEBSITE_BUCKET=$(echo "$RAW_WEBSITE" | grep -o 'auditor-dashboard-[0-9]*' | head -n 1)
          
          aws s3 cp ../BlockCICD_ABI.json s3://$ARTIFACT_BUCKET/contracts/BlockCICD_ABI.json
          
          CONTRACT_ADDR=$(grep 'contract_address' terraform.auto.tfvars | cut -d '"' -f 2)
          sed "s/REPLACE_ME_WITH_REAL_ADDRESS/$CONTRACT_ADDR/g" ../dashboard/index.html > index_final.html
          aws s3 cp index_final.html s3://$WEBSITE_BUCKET/index.html --content-type "text/html"
          
          echo "Dashboard Live at: http://$DASHBOARD_URL"